[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.89"
authors = ["CloudPSS"]
edition = "2024"
license = "MIT"
repository = "https://github.com/CloudPSS/MiraScript"
homepage = "https://mira.cloudpss.net"

[workspace.dependencies]
mirascript-core = { path = "crates/core", version = "=0.1.89" }
mirascript-vm = { path = "crates/vm", version = "=0.1.89" }
mirascript-vm-derive = { path = "crates/vm-derive", version = "=0.1.89" }

[profile.dev]
debug-assertions = true
debug = 2

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "debuginfo"
debug = "none"

[profile.profiling]
inherits = "release"
strip = "none"
debug = "line-tables-only"
