configDependencies:
  '@cloudpss/pnpm-plugin-config': '~4.0.6'

packages:
  - packages/*

allowBuilds:
  '@swc/core': true
  core-js: false
  esbuild: false

publicHoistPattern:
  # better-typescript-lib
  - '@typescript/*'
  # website
  - '@rspack/core'
  - 'unist-util-visit'
  - '@types/react'
  - '@types/react-dom'
  - '@types/mdast'
  - '@types/hast'
  - 'react'
  - 'react-dom'
  - 'prism-react-renderer'
  - '@docusaurus/*'

catalog:
  '@cloudpss/commitlint-config': ~4.0.6
  '@cloudpss/eslint-config': ~4.0.6
  '@cloudpss/lint-staged-config': ~4.0.6
  '@cloudpss/prettier-config': ~4.0.6
  '@cloudpss/tsconfig': ~4.0.6
