packages:
  - packages/*

ignoredBuiltDependencies:
  - eslint-config-prettier
  - esbuild
  - core-js
  - core-js-pure

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*commitlint*'
  - lint-staged
  - '@typescript/*'

shellEmulator: true
