packages:
  - packages/*

allowBuilds:
  '@swc/core': true
  core-js: false
  esbuild: false

configDependencies:
  '@cloudpss/pnpm-plugin-config': 'latest'

publicHoistPattern:
  # better-typescript-lib
  - '@typescript/*'
  # website
  - '@rspack/core'
  - 'unist-util-visit'
  - '@types/react'
  - '@types/react-dom'
  - '@types/mdast'
  - '@types/hast'
  - 'react'
  - 'react-dom'
  - 'prism-react-renderer'
  - '@docusaurus/*'
