[package]
name = "mirascript-python"
description = "Python native bindings for the MiraScript compiler"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "core"
crate-type = ["cdylib"]
doc = false

[features]
default = ["mimalloc"]
mimalloc = ["mirascript-core/mimalloc"]

[dependencies]
serde = "1"
mirascript-core = { workspace = true, features = ["serde"] }
pyo3 = { version = "0.29", features = ["abi3-py38", "abi3t-py315"] }
