[package]
name = "mirascript-vm"
description = "Native Rust virtual machine for MiraScript"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/mirascript-vm"
readme = "README.md"
keywords = ["mirascript", "interpreter", "scripting", "language", "vm"]
categories = ["compilers"]
publish = ["crates-io"]

[lib]
name = "mirascript_vm"

[[bench]]
name = "main"
harness = false

[dependencies]
indexmap = "2"
mirascript-core.workspace = true
mirascript-vm-derive.workspace = true
rand = "0.10"
serde_json = { version = "1", features = ["float_roundtrip", "preserve_order"] }
unicode-normalization = "0.1"

[dev-dependencies]
divan = "0.1.21"
trybuild = "1"
test_each_file = "0.3"
