[package]
name = "mirascript-wasm"
description = "MiraScript compiler for WebAssembly"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
  "-O4",
  "--enable-sign-ext",
  "--enable-bulk-memory",
  "--enable-mutable-globals",
  "--enable-nontrapping-float-to-int",
  # "--enable-simd",
]

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = [
  "-O4",
  "--enable-sign-ext",
  "--enable-bulk-memory",
  "--enable-mutable-globals",
  "--enable-nontrapping-float-to-int",
  # "--enable-simd",
]

[lib]
name = "wasm"
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error", "lsp"]
console_error = ["dep:console_error_panic_hook"]
lsp = ["mirascript-core/formatter"]

# [dev-dependencies]
# wasm-bindgen-test = "0.3.34"

[dependencies]
wasm-bindgen = "0.2"
mirascript-core = { workspace = true, features = ["wasm"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1", optional = true }
