[package]
name = "mirascript-napi"
description = "Node.js native bindings for the MiraScript compiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["mimalloc"]
mimalloc = ["mirascript-core/mimalloc"]

[dependencies]
napi = { version = "3", features = ["serde-json"] }
napi-derive = "3"
mirascript-core = { workspace = true, features = ["serde"] }

[build-dependencies]
napi-build = "2"
