import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { load } from 'js-yaml';

const packageRoot = path.resolve(import.meta.dirname, '..');
const srcRoot = path.join(packageRoot, 'src');
const distRoot = path.join(packageRoot, 'dist');

/**
 * Front-matter driven docs.
 *
 * Each markdown file under `src/keyword` and `src/operator` must have:
 *
 * ---
 * token: "..."   # actual token used in source code
 * order: 123      # used to keep generated output stable
 * ---
 */

/**
 * Read a markdown file under `src/`.
 * @param {string} relativePath
 * @returns {Promise<string>}
 */
async function readMarkdown(relativePath) {
    const fullPath = path.join(srcRoot, relativePath);
    return readFile(fullPath, 'utf8');
}

const FRONT_MATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/;

/**
 * Extract front-matter and strip it from markdown.
 * @param {string} markdown
 * @param {string} relativePath
 * @returns {{ attributes: Record<string, unknown>, body: string }}
 */
function splitFrontMatter(markdown, relativePath) {
    const m = FRONT_MATTER_RE.exec(markdown);
    if (!m) {
        throw new Error(`Missing front-matter in ${relativePath}. Add token/order mapping.`);
    }

    const attributes = load(m[1]);
    const body = markdown.slice(m[0].length);
    return { attributes, body };
}

/**
 * Load docs under a folder like `keyword` or `operator`.
 * @param {string} folder
 * @returns {Promise<Array<[string, string]>>}
 */
async function loadDocsFromFolder(folder) {
    const dirPath = path.join(srcRoot, folder);
    const dirents = await readdir(dirPath, { withFileTypes: true });

    /** @type {Array<{ token: string; order: number; body: string; file: string }>} */
    const items = [];

    for (const dirent of dirents) {
        if (!dirent.isFile()) continue;
        if (!dirent.name.endsWith('.md')) continue;

        const relativePath = path.posix.join(folder, dirent.name);
        const markdown = await readMarkdown(relativePath);
        const { attributes, body } = splitFrontMatter(markdown, relativePath);

        const { token, order } = attributes;
        if (typeof token !== 'string' || token.length === 0) {
            throw new TypeError(`Invalid front-matter field 'token' in ${relativePath}`);
        }
        if (typeof order !== 'number' || !Number.isFinite(order)) {
            throw new TypeError(`Invalid front-matter field 'order' in ${relativePath}`);
        }

        items.push({ token, order, body, file: relativePath });
    }

    items.sort((a, b) => a.order - b.order);

    const seenToken = new Set();
    /** @type {Array<[string, string]>} */
    const entries = [];
    for (const item of items) {
        if (seenToken.has(item.token)) {
            throw new Error(`Duplicate token '${item.token}' (found in ${item.file})`);
        }
        seenToken.add(item.token);
        entries.push([item.token, item.body]);
    }

    return entries;
}

/**
 * Render an object literal with string keys and raw markdown values.
 * @param {Array<[string, string]>} entries
 * @returns {string}
 */
function renderObjectLiteral(entries) {
    const lines = entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
    lines.unshift('  __proto__: null,');
    return `Object.freeze({\n${lines.join('\n')}\n})`;
}

/**
 * Render a `.d.ts` object type with explicit string-literal keys.
 * @param {Array<[string, string]>} entries
 * @returns {string}
 */
function renderDtsObjectType(entries) {
    const lines = entries.map(([k]) => `  readonly ${JSON.stringify(k)}: string;`);
    return `{\n${lines.join('\n')}\n}`;
}

/**
 * Build `dist/index.js` and `dist/index.d.ts`.
 * @returns {Promise<void>}
 */
async function main() {
    const keywordEntries = await loadDocsFromFolder('keyword');
    const operatorEntries = await loadDocsFromFolder('operator');

    await mkdir(distRoot, { recursive: true });

    const js = [
        '/* Generated by scripts/build.js. Do not edit manually. */',
        '',
        `export const KEYWORDS = ${renderObjectLiteral(keywordEntries)};`,
        `export const OPERATORS = ${renderObjectLiteral(operatorEntries)};`,
        '',
    ].join('\n');

    const dts = [
        '/* Generated by scripts/build.js. Do not edit manually. */',
        '',
        `export declare const KEYWORDS: ${renderDtsObjectType(keywordEntries)};`,
        `export declare const OPERATORS: ${renderDtsObjectType(operatorEntries)};`,
        '',
        'export type Keyword = keyof typeof KEYWORDS;',
        'export type Operator = keyof typeof OPERATORS;',
        '',
    ].join('\n');

    await writeFile(path.join(distRoot, 'index.js'), js, 'utf8');
    await writeFile(path.join(distRoot, 'index.d.ts'), dts, 'utf8');
}

main().catch((err) => {
    // eslint-disable-next-line no-console
    console.error(err);
    process.exitCode = 1;
});
