name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install
        with:
          ALIYUN_NPM_TOKEN: ${{ secrets.ALIYUN_NPM_TOKEN }}

      - name: Build
        run: pnpm -r run build

      - name: Pack website artifact
        run: |
          mv -f packages/website/build/ website-build/
          mv -f packages/playground/dist/ website-build/debug/

      - name: Build python sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          working-directory: crates/python

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v7
        with:
          name: website
          path: website-build/
          if-no-files-found: error

      - name: Upload npm package artifact
        uses: actions/upload-artifact@v7
        with:
          name: npm-package
          path: |
            packages/*/dist/
            packages/*/lib/
            !**/*.node
          if-no-files-found: error

      - name: Upload python sdist
        uses: actions/upload-artifact@v7
        with:
          name: python-sdist
          path: crates/python/dist/*
          if-no-files-found: error

  build-macos:
    needs: build
    runs-on: ${{ matrix.arch == 'x86_64' && 'macos-15-intel' || 'macos-latest' }}

    permissions:
      contents: read
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install
        with:
          ALIYUN_NPM_TOKEN: ${{ secrets.ALIYUN_NPM_TOKEN }}
          rust-targets: ${{ matrix.arch }}-apple-darwin

      - name: Download npm package artifact
        uses: actions/download-artifact@v8
        with:
          name: npm-package
          path: packages/

      - name: Build napi artifact
        run: |
          cd packages/napi
          pnpm run build --target ${{ matrix.arch }}-apple-darwin

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Build python wheel
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.arch }}-apple-darwin
          args: --release --out dist
          working-directory: crates/python

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14t
      - name: Build free-threaded python wheel
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.arch }}-apple-darwin
          args: --release --out dist -i python3.14t
          working-directory: crates/python

      - name: Upload napi artifact
        uses: actions/upload-artifact@v7
        with:
          name: napi-${{ matrix.arch }}-apple-darwin
          path: packages/napi/dist/*.node
          if-no-files-found: error

      - name: Upload python wheel artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-wheel-${{ matrix.arch }}-apple-darwin
          path: crates/python/dist/*.whl
          if-no-files-found: error

  build-windows:
    needs: build
    runs-on: ${{ matrix.arch == 'x86_64' && 'windows-latest' || 'windows-11-arm' }}

    permissions:
      contents: read
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install
        with:
          ALIYUN_NPM_TOKEN: ${{ secrets.ALIYUN_NPM_TOKEN }}
          rust-targets: ${{ matrix.arch }}-pc-windows-msvc

      - name: Download npm package artifact
        uses: actions/download-artifact@v8
        with:
          name: npm-package
          path: packages/

      - name: Build napi artifact
        run: |
          cd packages/napi
          pnpm run build --target ${{ matrix.arch }}-pc-windows-msvc

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Build python wheel
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.arch }}-pc-windows-msvc
          args: --release --out dist
          working-directory: crates/python

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14t
      - name: Build free-threaded python wheel
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.arch }}-pc-windows-msvc
          args: --release --out dist -i python3.14t
          working-directory: crates/python

      - name: Upload napi artifact
        uses: actions/upload-artifact@v7
        with:
          name: napi-${{ matrix.arch }}-pc-windows-msvc
          path: packages/napi/dist/*.node
          if-no-files-found: error

      - name: Upload python wheel artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-wheel-${{ matrix.arch }}-pc-windows-msvc
          path: crates/python/dist/*.whl
          if-no-files-found: error

  build-linux:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        libc: [gnu, musl]

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install
        with:
          ALIYUN_NPM_TOKEN: ${{ secrets.ALIYUN_NPM_TOKEN }}
          rust-targets: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          tools: cross

      - name: Download npm package artifact
        uses: actions/download-artifact@v8
        with:
          name: npm-package
          path: packages/

      - name: Build napi artifact
        run: |
          cd packages/napi
          pnpm run build --use-cross --target ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}

      - name: Build python wheel
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          args: --release --out dist
          working-directory: crates/python
          manylinux: ${{ matrix.libc == 'gnu' && '2_28' || 'musllinux_1_2' }}

      - name: Build free-threaded python wheel
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          args: --release --out dist -i python3.14t
          working-directory: crates/python
          manylinux: ${{ matrix.libc == 'gnu' && '2_28' || 'musllinux_1_2' }}

      - name: Upload napi artifact
        uses: actions/upload-artifact@v7
        with:
          name: napi-${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          path: packages/napi/dist/*.node
          if-no-files-found: error

      - name: Upload python wheel artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-wheel-${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          path: crates/python/dist/*.whl
          if-no-files-found: error

  build-all:
    needs: [build, build-macos, build-windows, build-linux]
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download npm package artifact
        uses: actions/download-artifact@v8
        with:
          name: npm-package
          path: packages/

      - name: Download napi artifact
        uses: actions/download-artifact@v8
        with:
          pattern: linux-napi-*
          merge-multiple: true
          path: packages/napi/dist/

      - name: Reupload npm package artifact
        uses: actions/upload-artifact@v7
        with:
          name: npm-package
          path: |
            packages/*/dist/
            packages/*/lib/
          if-no-files-found: error
          overwrite: true

      - name: Download wheel artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: python-*
          merge-multiple: true
          path: crates/python/dist/

      - name: Reupload python artifacts
        uses: actions/upload-artifact@v7
        with:
          name: python-artifacts
          path: crates/python/dist/*
          if-no-files-found: error

  test-node:
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-latest
          - macos-15-intel
        node:
          - 'lts/-1'
          - 'lts/*'
          # - 'latest'
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install
        with:
          ALIYUN_NPM_TOKEN: ${{ secrets.ALIYUN_NPM_TOKEN }}
          node-version: ${{ matrix.node }}

      - name: Download npm package artifact
        uses: actions/download-artifact@v8
        with:
          name: npm-package
          path: packages/

      - name: Run tests
        run: pnpm -r --if-present run test

  test-python:
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-latest
          - macos-15-intel
        python:
          - '3.7'
          - '3.14'
          - '3.14t'
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Download wheels
        uses: actions/download-artifact@v8
        with:
          name: python-artifacts
          path: crates/python/dist/

      - name: Run tests
        run: |
          cd crates/python
          pip install --no-index --find-links dist mirascript
          python -m unittest -b -c tests.black_box
