name: CI

on:
  push:
    branches-ignore: '*/*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read

    uses: ./.github/workflows/build.yml
    secrets: inherit

  code-scan:
    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install
        uses: ./.github/actions/install
        with:
          ALIYUN_NPM_TOKEN: ${{ secrets.ALIYUN_NPM_TOKEN }}
          rust-targets: x86_64-unknown-linux-gnu
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          tool: eslint
          format: sarif
          output: results.sarif
          upload: true
          gh-code-scanning-compat: true
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif

  deploy-pages:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v8
        with:
          name: website
          path: website-build/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: website-build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
