name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml

  deploy-pages:
    needs: build
    if: github.event_name == 'push'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v8
        with:
          name: website
          path: website-build/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: website-build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
